services:
  datomic:
    build:
      context: ./docker/datomic
      # Override if the default download URL changes.
      # args:
      #   DATOMIC_DOWNLOAD_URL: "https://datomic-pro-downloads.s3.amazonaws.com/1.0.7482/datomic-pro-1.0.7482.zip"
    container_name: the-big-counter-datomic
    ports:
      - "4334:4334"
    volumes:
      - datomic-data:/var/lib/datomic
      - datomic-logs:/var/log/datomic


volumes:
  datomic-data:
  datomic-logs:
